'use client';

import { useLocale } from 'next-intl';
import { Scale, AlertTriangle, FileText, Shield, RefreshCw, Clock, Ban, Mail } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';

export default function RefundPage() {
  const locale = useLocale();

  const sections = [
    {
      icon: Scale,
      title: '1. General Refund Principles',
      content: 'Due to the instant and automated nature of fund transfer networks (Mobile Money, banking gateways and Blockchain transactions), any transaction successfully executed and validated by partner networks is, in principle, final and irrevocable.',
    },
    {
      icon: AlertTriangle,
      title: '2. User Responsibility and Information Validation',
      content: 'Before confirming each transaction, a warning modal appears on the interface to recap the entered information. The user is strictly and exclusively responsible for verifying the accuracy of the provided details (Mobile Money phone number, PayPal email address, bank account number/SWIFT, crypto address). If a transaction is sent to incorrect external details entered by the user, PayMaestro cannot be held responsible, and no external refund can be made. Our systems have no control or withdrawal power over bank accounts or Mobile Money numbers managed by third-party operators.',
    },
    {
      icon: FileText,
      title: '3. Special Case — Internal Typo Error',
      content: 'If the user makes a typo and enters the number or identifier of another user already registered on PayMaestro, they must contact support immediately. If the claim is received in time, PayMaestro will intervene conservatively to temporarily freeze the erroneous recipient\'s PayMaestro account in order to block the funds and initiate an internal mediation procedure. If the funds have already been withdrawn from the platform by that recipient, PayMaestro can no longer interfere.',
    },
    {
      icon: RefreshCw,
      title: '4. Internal Refund Eligibility',
      content: 'A user may request a refund only in the following internal technical cases: Exclusive system technical error (involuntary double debit generated by the application, or funds effectively debited from the external source but not credited to the PayMaestro wallet within regulatory processing times). Third-party channel technical failure (transaction marked as definitively failed or suspended by a distribution partner while the user\'s source account was debited).',
    },
    {
      icon: Shield,
      title: '5. Fees and Commissions Treatment',
      content: 'Non-refundable service fees: when a commercial gesture or amicable resolution is granted following an error made by the user, PayMaestro transaction commissions and service fees (operator fees, FX commissions) are not refunded. They cover the technical fees charged by our infrastructure partners. Error attributable to PayMaestro: if the problem comes exclusively from an internal PayMaestro technical failure, the full gross amount (fees included) will be credited back to the user\'s account.',
    },
    {
      icon: Clock,
      title: '6. Unique Restitution Method: The PayMaestro Wallet',
      content: 'Any refund validated by our administration team is made exclusively as a credit to the user\'s PayMaestro wallet. No direct retrocession to an external bank account, external PayPal account or external Mobile Money network will be made by our administrators. The credit to the PayMaestro Wallet is immediate once the compliance team validates the anomaly on the administration console. It is then up to the user to re-initiate their withdrawal by ensuring correct details are entered.',
    },
    {
      icon: Ban,
      title: '7. Anti-Fraud and Chargeback Prevention',
      content: 'PayMaestro applies a zero-tolerance policy towards false declarations and abusive chargebacks. Any attempt to initiate an unjustified dispute with PayPal or a bank issuer for a correctly processed transaction on our platform will result in the immediate and definitive suspension of the PayMaestro account, total freezing of remaining assets for investigation, and registration of the user\'s identity on our anti-fraud watchlists.',
    },
    {
      icon: Mail,
      title: '8. Claim Procedure and Contact',
      content: 'The user must initiate an official claim via the platform chatbot or by writing to support@paymaestro.com within a maximum of 30 calendar days following the transaction date. The ticket must contain the unique transaction identifier (Order ID), the original debit proof from the issuing channel (operator SMS, bank receipt) and the clear reason for the request. The support team undertakes to analyze the file and provide a final response within 48 to 72 business hours.',
    },
  ];

  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <div className="text-center mb-10">
        <h1 className="text-4xl font-bold text-slate-900 dark:text-white mb-2">Refund and Dispute Resolution Policy</h1>
        <p className="text-slate-500 dark:text-slate-400">Last updated: July 2026</p>
      </div>

      <div className="bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800/50 rounded-2xl p-6 mb-8 text-center">
        <Scale className="w-8 h-8 text-amber-600 dark:text-amber-300 mx-auto mb-2" />
        <p className="text-sm text-amber-800 dark:text-amber-300 font-medium">
          At PayMaestro, we strive to provide a transparent, secure and reliable payment infrastructure. This policy defines the conditions, liability limits and procedures applicable to refund requests and dispute management within our platform.
        </p>
      </div>

      <div className="space-y-4">
        {sections.map((section) => (
          <Card key={section.title} className="border-slate-100 dark:border-slate-700">
            <CardContent className="p-6 space-y-3">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center">
                  <section.icon className="w-4 h-4 text-amber-600 dark:text-amber-300" />
                </div>
                <h3 className="font-bold text-slate-900 dark:text-white">{section.title}</h3>
              </div>
              <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed">{section.content}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="mt-8 text-center text-sm text-slate-400 dark:text-slate-500">
        <p>For urgent reports: <a href="mailto:support@paymaestro.com" className="text-violet-600 dark:text-violet-400 hover:underline">support@paymaestro.com</a></p>
      </div>
    </div>
  );
}
